/**
 * Bilingual UI copy for F-09. `const en: Copy = {...}` makes TypeScript enforce fa/en parity,
 * so a missing translation is a compile error (the same contract `content:check` enforces
 * for the content trees).
 */
const fa = {
  tabs: {
    analysis: "تحلیل توالی",
    convert: "تبدیل و ابزارها",
    pipeline: "Pipeline آزمایشگاه",
    fhir: "FHIR نمونه",
  },
  input: {
    label: "توالی DNA (FASTA یا خام)",
    placeholder: ">my-sequence\nATGCGTACGTTAGCTAGCTAGCATCGATCGTAGCTAGCTAGCTAGCATCGATCGATCGTAA",
    loadSample: "بار کردن نمونهٔ مرجع عمومی",
    sampleNote: "نمونه: ژن S ویروس SARS-CoV-2 (MN908947.3، دادهٔ عمومی، بدون هیچ دادهٔ بیمار)",
    openFile: "باز کردن فایل",
    fileHint: "پسوندهای مجاز: .fasta، .fa، .txt — حداکثر ۱ مگابایت",
    clear: "پاک کردن",
    analyze: "تحلیل کن",
    analyzing: "در حال تحلیل…",
    chars: "نوکلئوتید",
    header: "سرخط",
    invalidChars: "کاراکتر غیرمجاز",
    options: "گزینه‌ها",
    minOrf: "حداقل طول ORF (آمینواسید)",
    table: "جدول کدون",
    bothStrands: "هر دو رشته",
    gcThreshold: "آستانهٔ GC-غنی (٪)",
    worker: "اجرا در Web Worker",
    workerOff: "اجرای بدون Worker (جایگزین اصلی)",
    fileTooBig: "فایل بزرگ‌تر از ۱ مگابایت است. این نسخه سقف ۱ مگابایت دارد.",
    fileBadType: "فقط فایل‌های .fasta، .fa و .txt پذیرفته می‌شوند.",
    fileReadError: "خواندن فایل ممکن نشد. محتوا را دستی بچسبانید.",
  },
  results: {
    empty: "توالی‌ای تحلیل نشده است. توالی را بچسبانید یا نمونهٔ مرجع را بار کنید.",
    length: "طول",
    gc: "محتوای GC",
    at: "محتوای AT",
    skew: "چولگی GC",
    mw: "وزن مولکولی تقریبی",
    tm: "نقطهٔ ذوب (Tm)",
    tmWallace: "قاعدهٔ والاس (الیگو کوتاه)",
    tmGc: "فرمول GC با تصحیح نمک",
    counts: "شمارش بازها",
    ambiguous: "باز مبهم (N)",
    time: "زمان محاسبه",
    viewer: "نمایشگر توالی",
    viewerHint: "اسکرول = زوم · کشیدن = جابه‌جایی · ORF جلویی بالا، ORF پشتی پایین",
    zoomIn: "بزرگ‌نمایی",
    zoomOut: "کوچک‌نمایی",
    reset: "بازنشانی",
    window: "پنجره",
    orfTitle: "قاب‌های خواندن باز (ORF)",
    orfNone: "هیچ ORF با این حداقل طول پیدا نشد.",
    orfColumns: {
      coordinates: "موقعیت (۱-پایه)",
      frame: "قاب",
      strand: "رشته",
      length: "طول",
      aa: "آمینواسید",
      complete: "کامل",
      protein: "پروتئین",
    },
    forward: "جلویی",
    reverse: "پشتی",
    partial: "ناتمام (بدون کدون پایان)",
    complete: "کامل",
    codonTitle: "فراوانی کدون (per 1000)",
    codonColumns: { codon: "کدون", amino: "آمینواسید", count: "تعداد", perThousand: "در هزار" },
    regionsTitle: "مناطق GC-غنی",
    regionsNone: "منطقه‌ای بالای آستانه پیدا نشد.",
    regionColumns: { start: "شروع", end: "پایان", gc: "میانگین GC" },
    tableMode: "حالت جدول (کم‌مصرف): همهٔ محاسبات یکسان است، نمایشگر بومی غیرفعال شده.",
    tableCaption: "نمای جدولی توالی — همان دادهٔ نمایشگر بومی، بدون بوم.",
    tableRange: "بازه (۱-پایه)",
    tableGc: "میانگین GC",
    tableRegions: "مناطق GC-غنی",
    tableForward: "ORFهای رشتهٔ جلویی",
    tableReverse: "ORFهای رشتهٔ پشتی",
    download: "دانلود نتیجه",
    downloadJson: "JSON",
    downloadCsv: "CSV",
    share: "ساخت لینک اشتراک",
    shareUnavailable: "لینک اشتراک ساخته نشد (سرویس در دسترس نیست). نتیجه همچنان در مرورگر شما کار می‌کند.",
    shareReady: "لینک ساخته شد",
    shareCopy: "کپی لینک",
    sharePrivacy: "لینک اشتراک فقط خلاصه و اعداد را ذخیره می‌کند؛ توالی هرگز ذخیره نمی‌شود.",
  },
  convert: {
    reverseComplement: "مکمل معکوس",
    transcribe: "رونویسی (DNA → RNA)",
    translate: "ترجمه (پروتئین)",
    fasta: "قالب‌بندی FASTA",
    fastaId: "شناسه",
    fastaDescription: "توضیح",
    fastaWidth: "عرض خط",
    copy: "کپی",
    copied: "کپی شد",
    frame: "قاب",
    inputNote: "همان توالی تب تحلیل استفاده می‌شود؛ تبدیل‌ها لحظه‌ای و کاملاً محلی‌اند.",
    emptyInput: "برای تبدیل، اول در تب «تحلیل توالی» یک توالی وارد کنید.",
  },
  pipeline: {
    title: "خط لولهٔ نمونه → پذیرش → تست → نتیجه",
    intro: "این دیاگرام فقط با اعداد واقعیِ پیکربندی سایت رسم می‌شود. تا وقتی تیم اعداد را در پنل مدیریت وارد نکند، همین‌جا صریح «تنظیم‌نشده» می‌ماند.",
    stageIntake: "پذیرش نمونه",
    stageAccession: "ثبت و بارکد",
    stageTest: "اجرای تست",
    stageResult: "نتیجه و گزارش",
    samplesPerDay: "نمونه در روز",
    turnaround: "زمان چرخه",
    hours: "ساعت",
    testsPerSample: "تست برای هر نمونه",
    notConfigured: "تنظیم‌نشده",
    marker: "این اعداد از SiteConfig خوانده می‌شوند (قابل ویرایش در admin، بدون deploy).",
    offline: "پیکربندی سایت در دسترس نیست؛ اعداد نمایش داده نمی‌شوند.",
  },
  fhir: {
    title: "نمونهٔ FHIR (فقط دادهٔ ساختگی)",
    warning: "هیچ دادهٔ بیمار واقعی — نه در ورودی، نه در سرور، نه در این نمونه. همهٔ شناسه‌ها ساختگی‌اند.",
    intro: "سه منبع نمونه از نتیجهٔ تحلیل همین صفحه ساخته می‌شود: Patient، Observation و Encounter. اعتبارسنجی ساختاری محلی است و ادعای انطباق کامل با پروفایل ایران را ندارد.",
    validate: "اعتبارسنجی ساختاری",
    valid: "ساختار معتبر است",
    invalid: "ساختار ناقص است",
    missing: "فیلدهای غایب",
    resources: { patient: "Patient", observation: "Observation", encounter: "Encounter" },
    note: "این نمونه با پروفایل سلامت ایران مقایسهٔ کامل نشده است؛ فقط ساختار پایه بررسی می‌شود.",
  },
  notices: {
    disclaimer: "این ابزار برای پژوهش و آموزش است و جایگزین نرم‌افزار آزمایشگاهی یا تأیید بالینی نیست.",
    noPatientData: "هرگز دادهٔ واقعی بیمار وارد نکنید. توالی شما در مرورگر می‌ماند و ارسال/ذخیره نمی‌شود.",
    offlineOk: "همهٔ محاسبات محلی است؛ حتی اگر API قطع باشد این ابزار کامل کار می‌کند.",
    inputB10: "[ورودی B10] اعداد و داده‌های واقعی آزمایشگاه از تیم خواسته شده است.",
  },
};

export type BiolabCopy = typeof fa;

const en: BiolabCopy = {
  tabs: {
    analysis: "Sequence analysis",
    convert: "Convert & tools",
    pipeline: "Lab pipeline",
    fhir: "FHIR sample",
  },
  input: {
    label: "DNA sequence (FASTA or raw)",
    placeholder: ">my-sequence\nATGCGTACGTTAGCTAGCTAGCATCGATCGTAGCTAGCTAGCTAGCATCGATCGATCGTAA",
    loadSample: "Load public reference sample",
    sampleNote: "Sample: SARS-CoV-2 spike gene (MN908947.3, open data, no patient information)",
    openFile: "Open file",
    fileHint: "Allowed extensions: .fasta, .fa, .txt — up to 1 MB",
    clear: "Clear",
    analyze: "Analyse",
    analyzing: "Analysing…",
    chars: "nucleotides",
    header: "Header",
    invalidChars: "Illegal characters",
    options: "Options",
    minOrf: "Minimum ORF length (amino acids)",
    table: "Codon table",
    bothStrands: "Both strands",
    gcThreshold: "GC-rich threshold (%)",
    worker: "Running in a Web Worker",
    workerOff: "Running without a Worker (main-thread fallback)",
    fileTooBig: "The file is larger than 1 MB. This build caps at 1 MB.",
    fileBadType: "Only .fasta, .fa and .txt files are accepted.",
    fileReadError: "The file could not be read. Paste its content instead.",
  },
  results: {
    empty: "No sequence analysed yet. Paste one or load the reference sample.",
    length: "Length",
    gc: "GC content",
    at: "AT content",
    skew: "GC skew",
    mw: "Approx. molecular weight",
    tm: "Melting temperature (Tm)",
    tmWallace: "Wallace rule (short oligo)",
    tmGc: "GC formula with salt correction",
    counts: "Base counts",
    ambiguous: "Ambiguous bases (N)",
    time: "Compute time",
    viewer: "Sequence viewer",
    viewerHint: "Scroll = zoom · drag = pan · forward ORFs above, reverse ORFs below",
    zoomIn: "Zoom in",
    zoomOut: "Zoom out",
    reset: "Reset",
    window: "Window",
    orfTitle: "Open reading frames (ORFs)",
    orfNone: "No ORF reached the minimum length.",
    orfColumns: {
      coordinates: "Coordinates (1-based)",
      frame: "Frame",
      strand: "Strand",
      length: "Length",
      aa: "Amino acids",
      complete: "Complete",
      protein: "Protein",
    },
    forward: "Forward",
    reverse: "Reverse",
    partial: "Partial (no stop codon)",
    complete: "Complete",
    codonTitle: "Codon usage (per 1000)",
    codonColumns: { codon: "Codon", amino: "Amino acid", count: "Count", perThousand: "Per 1000" },
    regionsTitle: "GC-rich regions",
    regionsNone: "No region crossed the threshold.",
    regionColumns: { start: "Start", end: "End", gc: "Mean GC" },
    tableMode: "Table mode (low-power): every computation is identical, the native viewer is disabled.",
    tableCaption: "Tabular sequence view — the same data the native viewer draws, without a canvas.",
    tableRange: "Range (1-based)",
    tableGc: "Mean GC",
    tableRegions: "GC-rich regions",
    tableForward: "Forward-strand ORFs",
    tableReverse: "Reverse-strand ORFs",
    download: "Download result",
    downloadJson: "JSON",
    downloadCsv: "CSV",
    share: "Create share link",
    shareUnavailable: "The share link could not be created (service unavailable). Your result still works in this browser.",
    shareReady: "Link created",
    shareCopy: "Copy link",
    sharePrivacy: "A share link stores only the summary and numbers; the sequence itself is never stored.",
  },
  convert: {
    reverseComplement: "Reverse complement",
    transcribe: "Transcribe (DNA → RNA)",
    translate: "Translate (protein)",
    fasta: "FASTA formatter",
    fastaId: "Identifier",
    fastaDescription: "Description",
    fastaWidth: "Line width",
    copy: "Copy",
    copied: "Copied",
    frame: "Frame",
    inputNote: "The analysis-tab sequence is reused here; every conversion is instant and fully local.",
    emptyInput: "Enter a sequence in the ‘Sequence analysis’ tab first.",
  },
  pipeline: {
    title: "Sample → intake → test → result",
    intro: "This diagram only draws with real numbers from the site configuration. Until the team enters them in the admin, it stays an explicit ‘not configured’ state.",
    stageIntake: "Sample intake",
    stageAccession: "Accession & barcode",
    stageTest: "Test run",
    stageResult: "Result & report",
    samplesPerDay: "Samples per day",
    turnaround: "Turnaround",
    hours: "hours",
    testsPerSample: "Tests per sample",
    notConfigured: "Not configured",
    marker: "These numbers come from SiteConfig (editable in the admin, no deploy needed).",
    offline: "The site configuration is unreachable; numbers are not shown.",
  },
  fhir: {
    title: "FHIR sample (synthetic data only)",
    warning: "No real patient data — not in the input, not on the server, not in this sample. Every identifier is synthetic.",
    intro: "Three sample resources are generated from this page's analysis result: Patient, Observation and Encounter. Validation is structural and local; it does not claim full Iranian-profile conformance.",
    validate: "Structural validation",
    valid: "Structure is valid",
    invalid: "Structure is incomplete",
    missing: "Missing fields",
    resources: { patient: "Patient", observation: "Observation", encounter: "Encounter" },
    note: "This sample has not been fully compared with the Iranian health profile; only the base structure is checked.",
  },
  notices: {
    disclaimer: "This tool is for research and education and is not a substitute for laboratory software or clinical approval.",
    noPatientData: "Never enter real patient data. Your sequence stays in the browser and is never uploaded or stored.",
    offlineOk: "All computation is local; this tool keeps working even if the API is down.",
    inputB10: "[INPUT B10] Real lab numbers and datasets have been requested from the team.",
  },
};

export const biolabCopy: { fa: BiolabCopy; en: BiolabCopy } = { fa, en };
