# Generated by Django 5.2.17 on 2026-10-04 17:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_sitesettings_media_searchindexentry_translation'),
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='deleted at')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20, verbose_name='status')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='published at')),
                ('meta_title', models.CharField(blank=True, default='', max_length=70, verbose_name='meta title')),
                ('meta_title_fa', models.CharField(blank=True, default='', max_length=70, null=True, verbose_name='meta title')),
                ('meta_title_en', models.CharField(blank=True, default='', max_length=70, null=True, verbose_name='meta title')),
                ('meta_description', models.CharField(blank=True, default='', max_length=160, verbose_name='meta description')),
                ('meta_description_fa', models.CharField(blank=True, default='', max_length=160, null=True, verbose_name='meta description')),
                ('meta_description_en', models.CharField(blank=True, default='', max_length=160, null=True, verbose_name='meta description')),
                ('canonical_path', models.CharField(blank=True, default='', help_text='در صورت خالی بودن، مسیر پیش\u200cفرض صفحه به\u200cعنوان canonical استفاده می\u200cشود.', max_length=255, verbose_name='canonical path')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('title_fa', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='slug')),
                ('excerpt', models.CharField(max_length=300, verbose_name='excerpt')),
                ('excerpt_fa', models.CharField(max_length=300, null=True, verbose_name='excerpt')),
                ('excerpt_en', models.CharField(max_length=300, null=True, verbose_name='excerpt')),
                ('content', models.TextField(blank=True, default='', verbose_name='content (Markdown)')),
                ('content_fa', models.TextField(blank=True, default='', null=True, verbose_name='content (Markdown)')),
                ('content_en', models.TextField(blank=True, default='', null=True, verbose_name='content (Markdown)')),
                ('content_html', models.TextField(blank=True, default='', editable=False)),
                ('content_html_fa', models.TextField(blank=True, default='', editable=False, null=True)),
                ('content_html_en', models.TextField(blank=True, default='', editable=False, null=True)),
                ('reading_time_minutes', models.PositiveIntegerField(default=0, editable=False, verbose_name='reading time (minutes)')),
                ('view_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='view count')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, related_name='blog_posts', to='taxonomy.category')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.media')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.media', verbose_name='OG image')),
                ('tags', models.ManyToManyField(blank=True, related_name='blog_posts', to='taxonomy.tag')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='deleted at')),
                ('body', models.TextField(max_length=3000, verbose_name='body')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20, verbose_name='status')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogpost')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['slug'], name='blog_blogpo_slug_361555_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'status'], name='blog_commen_post_id_651007_idx'),
        ),
    ]
