# Generated by Django 5.2.17 on 2026-10-04 17:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_sitesettings_media_searchindexentry_translation'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='deleted at')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20, verbose_name='status')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='published at')),
                ('meta_title', models.CharField(blank=True, default='', max_length=70, verbose_name='meta title')),
                ('meta_title_fa', models.CharField(blank=True, default='', max_length=70, null=True, verbose_name='meta title')),
                ('meta_title_en', models.CharField(blank=True, default='', max_length=70, null=True, verbose_name='meta title')),
                ('meta_description', models.CharField(blank=True, default='', max_length=160, verbose_name='meta description')),
                ('meta_description_fa', models.CharField(blank=True, default='', max_length=160, null=True, verbose_name='meta description')),
                ('meta_description_en', models.CharField(blank=True, default='', max_length=160, null=True, verbose_name='meta description')),
                ('canonical_path', models.CharField(blank=True, default='', help_text='در صورت خالی بودن، مسیر پیش\u200cفرض صفحه به\u200cعنوان canonical استفاده می\u200cشود.', max_length=255, verbose_name='canonical path')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('title_fa', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='slug')),
                ('summary', models.CharField(max_length=300, verbose_name='summary')),
                ('summary_fa', models.CharField(max_length=300, null=True, verbose_name='summary')),
                ('summary_en', models.CharField(max_length=300, null=True, verbose_name='summary')),
                ('description', models.TextField(blank=True, default='', verbose_name='description (Markdown)')),
                ('description_fa', models.TextField(blank=True, default='', null=True, verbose_name='description (Markdown)')),
                ('description_en', models.TextField(blank=True, default='', null=True, verbose_name='description (Markdown)')),
                ('description_html', models.TextField(blank=True, default='', editable=False, verbose_name='description (HTML, cached)')),
                ('description_html_fa', models.TextField(blank=True, default='', editable=False, null=True, verbose_name='description (HTML, cached)')),
                ('description_html_en', models.TextField(blank=True, default='', editable=False, null=True, verbose_name='description (HTML, cached)')),
                ('icon', models.CharField(blank=True, default='', help_text='نام آیکون lucide-react.', max_length=50, verbose_name='icon')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='order')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='is featured')),
                ('categories', models.ManyToManyField(blank=True, related_name='services', to='taxonomy.category')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.media', verbose_name='OG image')),
                ('tags', models.ManyToManyField(blank=True, related_name='services', to='taxonomy.tag')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'title'],
                'abstract': False,
            },
        ),
    ]
