# Generated by Django 5.2.17 on 2026-10-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='kind',
            field=models.CharField(choices=[('scan', 'Scan'), ('ask', 'Ask'), ('embed', 'Embed'), ('og_image', 'Open Graph image'), ('digest', 'Digest')], db_index=True, max_length=32),
        ),
    ]
