# Generated by Django 5.2.17 on 2026-10-04 17:36

import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Emmett', max_length=100, verbose_name='site name')),
                ('site_name_fa', models.CharField(default='Emmett', max_length=100, null=True, verbose_name='site name')),
                ('site_name_en', models.CharField(default='Emmett', max_length=100, null=True, verbose_name='site name')),
                ('default_locale', models.CharField(default='fa', max_length=5, verbose_name='default locale')),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='contact email')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='contact phone')),
                ('social_links', models.JSONField(blank=True, default=dict, verbose_name='social links')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='maintenance mode')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='deleted at')),
                ('file', models.FileField(upload_to=apps.core.models.media_upload_path, verbose_name='file')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('video', 'Video')], max_length=20, verbose_name='media type')),
                ('alt_text', models.CharField(blank=True, default='', max_length=255, verbose_name='alt text')),
                ('alt_text_fa', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='alt text')),
                ('alt_text_en', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='alt text')),
                ('caption', models.CharField(blank=True, default='', max_length=255, verbose_name='caption')),
                ('caption_fa', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='caption')),
                ('caption_en', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='caption')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='width')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='height')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='file size (bytes)')),
                ('mime_type', models.CharField(blank=True, default='', max_length=100, verbose_name='MIME type')),
                ('checksum', models.CharField(blank=True, default='', max_length=64, verbose_name='checksum (sha256)')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SearchIndexEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(db_index=True, max_length=30, verbose_name='content type')),
                ('object_id', models.PositiveBigIntegerField(verbose_name='object id')),
                ('public_id', models.UUIDField(verbose_name='public id')),
                ('locale', models.CharField(choices=[('fa', 'فارسی'), ('en', 'English')], max_length=5, verbose_name='locale')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('body', models.TextField(blank=True, default='', verbose_name='body')),
                ('url_path', models.CharField(max_length=255, verbose_name='URL path')),
                ('category_label', models.CharField(blank=True, default='', max_length=100, verbose_name='category label')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Search Index Entry',
                'verbose_name_plural': 'Search Index Entries',
                'indexes': [models.Index(fields=['content_type', 'locale'], name='core_search_content_307cef_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'locale'), name='unique_search_index_entry')],
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(db_index=True, max_length=100, verbose_name='namespace')),
                ('key', models.CharField(max_length=150, verbose_name='key')),
                ('locale', models.CharField(choices=[('fa', 'فارسی'), ('en', 'English')], max_length=5, verbose_name='locale')),
                ('value', models.TextField(blank=True, default='', verbose_name='value')),
                ('is_html', models.BooleanField(default=False, verbose_name='is HTML')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Translation',
                'verbose_name_plural': 'Translations',
                'constraints': [models.UniqueConstraint(fields=('namespace', 'key', 'locale'), name='unique_translation_entry')],
            },
        ),
    ]
