# Generated by Django 5.2.17 on 2026-10-04 19:21

import apps.core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_search_fulltext_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to=apps.core.models.media_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'svg', 'pdf', 'docx'])], verbose_name='file'),
        ),
    ]
