# Generated by Django 5.2.17 on 2026-10-05 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_media_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description',
            field=models.CharField(blank=True, default='', help_text='Aim for 120–160 characters; longer text is truncated by search engines.', max_length=320, verbose_name='default meta description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description_en',
            field=models.CharField(blank=True, default='', help_text='Aim for 120–160 characters; longer text is truncated by search engines.', max_length=320, null=True, verbose_name='default meta description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description_fa',
            field=models.CharField(blank=True, default='', help_text='Aim for 120–160 characters; longer text is truncated by search engines.', max_length=320, null=True, verbose_name='default meta description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_title',
            field=models.CharField(blank=True, default='', help_text='Used for pages without their own SEO title.', max_length=200, verbose_name='default meta title'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_title_en',
            field=models.CharField(blank=True, default='', help_text='Used for pages without their own SEO title.', max_length=200, null=True, verbose_name='default meta title'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_title_fa',
            field=models.CharField(blank=True, default='', help_text='Used for pages without their own SEO title.', max_length=200, null=True, verbose_name='default meta title'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='og_default_image',
            field=models.ForeignKey(blank=True, help_text='Used by social cards when a page has no image of its own (1200×630 recommended).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.media', verbose_name='default Open Graph image'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='organization_address',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='organization address'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='organization_address_en',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='organization address'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='organization_address_fa',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='organization address'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='organization_legal_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='legal organization name'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='organization_legal_name_en',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='legal organization name'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='organization_legal_name_fa',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='legal organization name'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='organization_same_as',
            field=models.JSONField(blank=True, default=list, help_text='Public profile URLs used in JSON-LD, e.g. LinkedIn or GitHub.', verbose_name='organization same-as URLs'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='search_console_verification',
            field=models.CharField(blank=True, default='', help_text='Content value of the google-site-verification meta tag.', max_length=200, verbose_name='Google Search Console verification code'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter_handle',
            field=models.CharField(blank=True, default='', help_text='Example: @emmett', max_length=50, verbose_name='Twitter/X handle'),
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='deleted at')),
                ('path', models.CharField(db_index=True, max_length=255, verbose_name='page path')),
                ('question', models.CharField(max_length=300, verbose_name='question')),
                ('question_fa', models.CharField(max_length=300, null=True, verbose_name='question')),
                ('question_en', models.CharField(max_length=300, null=True, verbose_name='question')),
                ('answer', models.TextField(verbose_name='answer')),
                ('answer_fa', models.TextField(null=True, verbose_name='answer')),
                ('answer_en', models.TextField(null=True, verbose_name='answer')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'FAQ item',
                'verbose_name_plural': 'FAQ items',
                'ordering': ['path', 'order', 'id'],
                'abstract': False,
                'indexes': [models.Index(fields=['path', 'order'], name='core_faqite_path_316fb3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='deleted at')),
                ('from_path', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='from path')),
                ('target', models.CharField(blank=True, default='', help_text='Relative path (e.g. /services/web/) or an absolute https:// URL.', max_length=500, verbose_name='target')),
                ('status_code', models.PositiveSmallIntegerField(choices=[(301, '301 — Permanent'), (302, '302 — Temporary'), (410, '410 — Removed permanently')], default=301, verbose_name='status code')),
                ('hit_count', models.PositiveBigIntegerField(default=0, editable=False, verbose_name='hit count')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='note')),
            ],
            options={
                'verbose_name': 'Redirect',
                'verbose_name_plural': 'Redirects',
                'ordering': ['from_path'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('from_path__startswith', '/')), name='redirect_from_path_is_rooted'), models.CheckConstraint(condition=models.Q(('status_code__in', [301, 302, 410])), name='redirect_status_is_supported')],
            },
        ),
    ]
