/**
 * Bilingual copy for the tool shell, palette, terminal and share pages.
 * `content:check` compares the fa/en trees key by key, so a missing translation fails CI.
 */
export const toolsCopy = {
  fa: {
    index: {
      title: "جعبه‌ابزار امت",
      eyebrow: "ابزارهای زنده، نه اسکرین‌شات",
      intro: "هر ابزار همین‌جا اجرا می‌شود: بدون ثبت‌نام، بدون ارسال دادهٔ حساس، با کد واقعی و لینک اشتراکی.",
      search: "جست‌وجوی ابزار…",
      empty: "ابزاری با این عبارت پیدا نشد.",
      open: "باز کردن ابزار",
      capability: "توان",
      all: "همه",
      toolsCount: "ابزار زنده",
      offlineFirst: "منطق اصلی سمت کلاینت اجرا می‌شود؛ اگر API قطع باشد ابزار از کار نمی‌افتد.",
    },
    tool: {
      version: "نسخه",
      updated: "آخرین به‌روزرسانی",
      howItWorks: "چطور کار می‌کند",
      code: "کد واقعی",
      copy: "کپی",
      copied: "کپی شد",
      share: "ساخت لینک اشتراک",
      shareUnavailable: "برای ساختن لینک اشتراک، سرویس در دسترس نیست. می‌توانید نتیجه را همین‌جا کپی کنید.",
      shareReady: "لینک اشتراک ساخته شد",
      shareCopy: "کپی لینک",
      related: "ابزارهای مرتبط",
      backToTools: "همهٔ ابزارها",
      resultNoindex: "صفحهٔ نتیجه در موتور جست‌وجو ایندکس نمی‌شود (noindex).",
      disclaimer: "توجه",
      lowPowerNote: "در حالت کم‌مصرف جلوه‌ها حذف می‌شوند، ولی همهٔ محاسبات کامل انجام می‌شود.",
      loadError: "این بخش بارگذاری نشد. صفحه را دوباره باز کنید.",
      retry: "تلاش دوباره",
    },
    shell: {
      paletteTitle: "پالت فرمان امت",
      paletteDescription: "جست‌وجوی صفحات، ابزارها و دستورها",
      palettePlaceholder: "چه کاری می‌خواهید انجام دهید؟ مثلاً «کد ملی» یا sec",
      paletteEmpty: "نتیجه‌ای پیدا نشد. با ? راهنمای میان‌برها را ببینید.",
      groups: { pages: "صفحات", tools: "ابزارها", commands: "دستورها", team: "تیم", cases: "کیس‌استادی‌ها" },
      openTerminal: "باز کردن ترمینال",
      close: "بستن",
      helpTitle: "میان‌برهای کیبورد",
      helpDescription: "همهٔ بخش‌های سایت با کیبورد قابل دسترسی است.",
      shortcuts: {
        palette: "باز/بستن پالت فرمان",
        terminal: "باز/بستن ترمینال",
        help: "همین راهنما",
        escape: "بستن لایه‌ها",
        tabs: "پیمایش نتایج",
      },
    },
    terminal: {
      title: "ترمینال امت",
      hint: "برای فهرست دستورها help را بزنید. Tab تکمیل می‌کند و ↑ تاریخچه را می‌آورد.",
      placeholder: "دستور…",
      run: "اجرا",
      clear: "پاک کردن",
      close: "بستن",
      noscript: "ترمینال به جاوااسکریپت نیاز دارد. فهرست دستورها و ابزارها به‌صورت لینک در همین صفحه در دسترس است.",
      unknown: "دستور ناشناخته. برای دیدن فهرست دستورها help را بزنید.",
      blocked: "این دستور مجاز نیست. ترمینال فقط دستورهای فهرست‌شده را اجرا می‌کند و هیچ کدی اجرا نمی‌شود.",
      apiError: "اجرای دستور با خطا مواجه شد؛ پیام سرویس در بالا آمده است.",
      offline: "سرویس در دسترس نیست. دستورهای محلی (help، open، theme، lang) همچنان کار می‌کنند.",
      consentPrompt: "برای اسکن دامنه باید مالک آن باشی یا اجازه داشته باشی. تایپ کن: scan <domain> --consent",
      scanSoon: "دستور scan در فاز بعد فعال می‌شود (فاز ۳).",
      askSoon: "دستور ask در فاز بعد فعال می‌شود (فاز ۳).",
      noResults: "موردی برگشت داده نشد.",
    },
    scanner: {
      eyebrow: "بررسی passive، بدون دسترسی",
      title: "چک‌آپ امنیتی دامنه",
      intro: "شش بخش عمومی دامنه را بررسی می‌کنیم: هدرها، TLS، DNS، کوکی‌ها، قرارگیری محتوا و نشت اطلاعات. هیچ پورت‌اسکن، payload یا تلاش نفوذی انجام نمی‌شود.",
      disclaimer: "این بررسی فقط اطلاعات عمومی را می‌خواند و هیچ دسترسی یا تلاش برای نفوذ انجام نمی‌دهد. فقط دامنه‌ای را بررسی کنید که مالک آن هستید یا اجازه دارید (مادهٔ ۷۲۹ قانون مجازات اسلامی).",
      consent: "مالک این دامنه هستم یا اجازه دارم",
      consentNote: "بدون تأیید این تیک، دکمهٔ بررسی فعال نمی‌شود.",
      domain: "دامنه",
      domainPlaceholder: "example.com",
      submit: "شروع بررسی",
      queueNote: "بررسی در پس‌زمینه انجام می‌شود؛ این صفحه هر چند لحظه یک‌بار وضعیت را می‌پرسد.",
      steps: { dns: "رکوردهای DNS", tls: "TLS و گواهی", headers: "هدرهای امنیتی", cookies: "کوکی‌ها", content: "قرارگیری محتوا", leak: "نشت اطلاعات" },
      running: "در حال بررسی…",
      queued: "در صف بررسی قرار گرفت. تا چند لحظه دیگر نتیجه آماده می‌شود.",
      resultTitle: "گزارش بررسی",
      grade: "گرید",
      score: "نمره",
      sections: "بخش‌ها",
      recommendations: "توصیه‌ها",
      snippet: "نمونهٔ پیکربندی",
      reportLink: "لینک دائمی گزارش",
      newScan: "بررسی دامنهٔ دیگر",
      noindexNote: "این گزارش یک لینک دائمی noindex است و پس از ۷ روز حذف می‌شود.",
      invalidDomain: "دامنهٔ وارد‌شده معتبر نیست. نمونه: example.com",
      rateLimited: "سقف بررسی در ساعت پر شده است. کمی بعد دوباره تلاش کنید.",
      failedTitle: "این بخش بررسی نشد",
      failedBody: "اتصال برقرار نشد؛ بقیهٔ بخش‌ها بررسی شدند و نتیجه معتبر است.",
      degradedTitle: "صف بررسی شلوغ است",
      degradedBody: "نتیجه تا چند دقیقه دیگر آماده می‌شود. تا آن زمان می‌توانید گزارش‌های نمونه را ببینید.",
      ctaTitle: "گزارش کامل + تست نفوذ واقعی",
      ctaBody: "این بررسی فقط سطح عمومی را می‌بیند. برای پیدا کردن آسیب‌پذیری‌های واقعی، تست نفوذ انجام می‌دهیم.",
      ctaButton: "گفتگو با تیم PenTestor",
      evidenceNote: "هر یافته در سرور با یک بررسی واقعی تولید شده است؛ در نسخهٔ عمومی نسخهٔ دقیق سرویس‌دهنده ماسک می‌شود.",
    },
    assistant: {
      eyebrow: "RAG روی محتوای واقعی امت",
      title: "دستیار امت",
      intro: "فقط از روی مطالب خود امت جواب می‌دهم؛ هر پاسخ ارجاع دارد و اگر پیدا نکنم، صریح می‌گویم.",
      placeholder: "مثلاً: پن‌تستور چطور کار می‌کند؟",
      ask: "بپرس",
      thinking: "در حال جست‌وجو در مطالب…",
      suggestions: "پیشنهاد پرسش",
      disclosure: "این پاسخ توسط مدل زبانی و فقط از روی مطالب امت تولید شده و ممکن است خطا داشته باشد.",
      notFound: "این را در مطالب ما پیدا نکردم.",
      degraded: "پاسخ هوشمند موقتاً در دسترس نیست؛ این مطالب مرتبط را پیدا کردیم.",
      modeLlm: "پاسخ هوشمند",
      modeBm25: "جست‌وجوی متنی (BM25)",
      modeNotFound: "بدون پاسخ در کورپوس",
      citations: "منابع",
      showWork: "چه چیزی پیدا شد؟",
      hideWork: "پنهان کردن جزئیات",
      feedback: "این پاسخ مفید بود؟",
      helpful: "بله",
      notHelpful: "خیر",
      thanks: "ممنون؛ فقط همین سیگنال ثبت شد، بدون متن پرسش.",
      openChat: "باز کردن دستیار",
      close: "بستن",
      clear: "گفت‌وگوی جدید",
      limitNote: "حداکثر ۵۰۰ کاراکتر · ۲۰ پرسش در ساعت · متن پرسش بدون رضایت شما ذخیره نمی‌شود.",
      widgetTitle: "دستیار امت",
      errorGeneric: "ارتباط با دستیار برقرار نشد. کمی بعد دوباره تلاش کنید.",
      cached: "از پاسخ ذخیره‌شده",
      noCitations: "پاسخ بدون ارجاع نمایش داده نمی‌شود.",
    },
    share: {
      eyebrow: "لینک دائمی",
      title: "نتیجهٔ اشتراکی",
      description: "این صفحه یک نتیجهٔ ذخیره‌شده را نشان می‌دهد؛ خودِ محاسبه دوباره در مرورگر شما اجرا می‌شود و ورودی شما ذخیره نمی‌شود.",
      loading: "در حال خواندن نتیجه…",
      notFound: "این لینک اشتراکی پیدا نشد یا هنوز در دسترس نیست.",
      tool: "ابزار",
      summary: "خلاصهٔ نتیجه",
      params: "پارامترها",
      noindexNote: "این صفحه noindex است و یک لینک دائمی برای اشتراک‌گذاری است.",
      openTool: "باز کردن ابزار با همین ورودی",
      backHome: "بازگشت به خانه",
    },
  },
  en: {
    index: {
      title: "Emmett toolbox",
      eyebrow: "Live tools, not screenshots",
      intro: "Every tool runs here: no sign-up, no sensitive data uploaded, with real code and a share link.",
      search: "Search tools…",
      empty: "No tool matches that phrase.",
      open: "Open tool",
      capability: "Capability",
      all: "All",
      toolsCount: "live tools",
      offlineFirst: "Core logic runs client-side, so the tools keep working when the API is down.",
    },
    tool: {
      version: "Version",
      updated: "Last updated",
      howItWorks: "How it works",
      code: "Real code",
      copy: "Copy",
      copied: "Copied",
      share: "Create share link",
      shareUnavailable: "Sharing service is unavailable. You can copy the result right here instead.",
      shareReady: "Share link created",
      shareCopy: "Copy link",
      related: "Related tools",
      backToTools: "All tools",
      resultNoindex: "Result pages are noindex and never appear in search engines.",
      disclaimer: "Note",
      lowPowerNote: "Low-power mode removes the effects, never the calculations.",
      loadError: "This section failed to load. Reload the page to try again.",
      retry: "Retry",
    },
    shell: {
      paletteTitle: "Emmett command palette",
      paletteDescription: "Search pages, tools and commands",
      palettePlaceholder: "What do you want to do? Try “national id” or sec",
      paletteEmpty: "Nothing found. Press ? for keyboard shortcuts.",
      groups: { pages: "Pages", tools: "Tools", commands: "Commands", team: "Team", cases: "Case studies" },
      openTerminal: "Open terminal",
      close: "Close",
      helpTitle: "Keyboard shortcuts",
      helpDescription: "Every surface is reachable from the keyboard.",
      shortcuts: {
        palette: "Open/close the command palette",
        terminal: "Open/close the terminal",
        help: "This help",
        escape: "Close overlays",
        tabs: "Move through results",
      },
    },
    terminal: {
      title: "Emmett terminal",
      hint: "Type help for the command list. Tab completes, ↑ walks the history.",
      placeholder: "command…",
      run: "Run",
      clear: "Clear",
      close: "Close",
      noscript: "The terminal needs JavaScript. The same commands are available as plain links on this page.",
      unknown: "Unknown command. Type help to see the allow-list.",
      blocked: "That command is not allowed. The terminal only runs allow-listed commands and never evaluates code.",
      apiError: "The command failed; the service message is shown above.",
      offline: "Service is unavailable. Local commands (help, open, theme, lang) still work.",
      consentPrompt: "Scanning a domain requires that you own it or have permission. Type: scan <domain> --consent",
      scanSoon: "The scan command is activated in the next phase (Phase 3).",
      askSoon: "The ask command is activated in the next phase (Phase 3).",
      noResults: "No rows returned.",
    },
    scanner: {
      eyebrow: "Passive check, no access",
      title: "Domain security check-up",
      intro: "We inspect six public surfaces: headers, TLS, DNS, cookies, content placement and information leaks. No port scan, no payload, no intrusion attempt.",
      disclaimer: "This check only reads public information and performs no access or intrusion attempt. Only scan a domain you own or are allowed to test (Article 729 of the Iranian Penal Code).",
      consent: "I own this domain or have permission",
      consentNote: "The scan button stays disabled until you confirm this.",
      domain: "Domain",
      domainPlaceholder: "example.com",
      submit: "Start check",
      queueNote: "The check runs in the background; this page polls the state every few seconds.",
      steps: { dns: "DNS records", tls: "TLS and certificate", headers: "Security headers", cookies: "Cookies", content: "Content placement", leak: "Information leaks" },
      running: "Checking…",
      queued: "Queued for checking. The result will be ready shortly.",
      resultTitle: "Check report",
      grade: "Grade",
      score: "Score",
      sections: "Sections",
      recommendations: "Recommendations",
      snippet: "Configuration snippet",
      reportLink: "Permanent report link",
      newScan: "Check another domain",
      noindexNote: "This report is a permanent noindex link and is deleted after 7 days.",
      invalidDomain: "That domain is not valid. Example: example.com",
      rateLimited: "The hourly check limit is reached. Please try again later.",
      failedTitle: "This section was not checked",
      failedBody: "The connection failed; the other sections were checked and the result is still valid.",
      degradedTitle: "The queue is busy",
      degradedBody: "The result will be ready in a few minutes. Meanwhile you can look at the sample reports.",
      ctaTitle: "Full report + real penetration test",
      ctaBody: "This check only sees the public surface. To find real vulnerabilities we run an actual penetration test.",
      ctaButton: "Talk to the PenTestor team",
      evidenceNote: "Every finding comes from a real check on the server; in the public version the exact software version is masked.",
    },
    assistant: {
      eyebrow: "RAG on Emmett's real material",
      title: "Emmett assistant",
      intro: "I answer only from Emmett's own material; every answer carries a citation, and when I cannot find it I say so.",
      placeholder: "For example: How does PenTestor work?",
      ask: "Ask",
      thinking: "Searching the material…",
      suggestions: "Suggested questions",
      disclosure: "This answer was generated by a language model from Emmett's own material and may contain mistakes.",
      notFound: "I could not find this in our material.",
      degraded: "The AI answer is temporarily unavailable; here is the related material we found.",
      modeLlm: "AI answer",
      modeBm25: "Text search (BM25)",
      modeNotFound: "Not in the corpus",
      citations: "Sources",
      showWork: "What was found?",
      hideWork: "Hide the details",
      feedback: "Was this answer helpful?",
      helpful: "Yes",
      notHelpful: "No",
      thanks: "Thanks — only that signal was stored, never your question text.",
      openChat: "Open the assistant",
      close: "Close",
      clear: "New conversation",
      limitNote: "Max 500 characters · 20 questions per hour · your question is not stored without consent.",
      widgetTitle: "Emmett assistant",
      errorGeneric: "The assistant could not be reached. Please try again shortly.",
      cached: "From the answer cache",
      noCitations: "An answer without citations is never displayed.",
    },
    share: {
      eyebrow: "Permanent link",
      title: "Shared result",
      description: "This page shows a stored result; the calculation itself still runs in your browser and your input is never uploaded.",
      loading: "Loading the shared result…",
      notFound: "That share link was not found, or it is not available yet.",
      tool: "Tool",
      summary: "Result summary",
      params: "Parameters",
      noindexNote: "This page is noindex and is a permanent sharing link.",
      openTool: "Open the tool with the same input",
      backHome: "Back to home",
    },
  },
} as const;

export type ToolsCopy = typeof toolsCopy.fa;
