import type { ToolMeta } from "@/features/toolbox/types";

/** F-08 is a page with a widget, but it reuses the tool contract so the palette, SEO and
 *  the G1 evidence gate treat it exactly like the other capabilities. */
export const meta: ToolMeta = {
  id: "assistant",
  slug: { fa: "assistant", en: "assistant" },
  title: { fa: "دستیار امت", en: "Emmett assistant" },
  subtitle: {
    fa: "RAG روی محتوای واقعی امت، با ارجاع و «نمی‌دانم» صادقانه.",
    en: "RAG on Emmett's real material, with citations and an honest “I don't know”.",
  },
  description: {
    fa: "دستیار فقط از روی مطالب خود امت جواب می‌دهد، هر پاسخ را با ارجاع به منبع نشان می‌دهد و وقتی کورپوس پاسخ ندارد صریح می‌گوید پیدا نکردم. با BM25 کار می‌کند و provider مدل زبانی از طریق ADR-007 قابل تعویض است.",
    en: "The assistant answers only from Emmett's own material, shows a source for every answer, and says so when the corpus has no answer. It works on BM25, with the LLM provider swappable through ADR-007.",
  },
  capability: "ai",
  version: "1.0.0",
  updatedFa: "۱۴۰۵/۰۷/۱۰",
  keywords: {
    fa: ["دستیار", "هوش مصنوعی", "رگ", "پرسش", "ارجاع", "کورپوس"],
    en: ["assistant", "ai", "rag", "question", "citations", "corpus"],
  },
  evidence: {
    fa: "آستانهٔ شباهت پیش از تماس با مدل اعمال می‌شود و پاسخ بی‌ارجاع نمایش داده نمی‌شود.",
    en: "The similarity threshold runs before any model call, and an answer without citations is never shown.",
  },
  howItWorks: {
    fa: [
      "کورپوس از همان فایل‌هایی ساخته می‌شود که سایت را رندر می‌کنند: کپی صفحات، توضیح ابزارها و FAQ با برچسب [INPUT] برای موارد تأییدنشده.",
      "کرون شبانه فقط chunkهای تغییرکرده را دوباره embedding می‌کند؛ جست‌وجو با BM25 و در صورت وجود provider با cosine در حافظه انجام می‌شود.",
      "اگر هیچ chunk بالای آستانه نباشد، هیچ تماسی با مدل زبانی زده نمی‌شود و پاسخ «پیدا نکردم» برمی‌گردد.",
    ],
    en: [
      "The corpus is built from the very files that render the site: page copy, tool descriptions and FAQ entries, with [INPUT] markers for anything unconfirmed.",
      "A nightly cron re-embeds only changed chunks; search uses BM25, and cosine in memory when a provider exists.",
      "If no chunk clears the threshold, no model call happens at all and the answer is “I could not find this”.",
    ],
  },
  codeSamples: [
    {
      label: "guard · answers.py",
      language: "python",
      code: `result = search(question, locale=locale)
if not hits:
    return {"answer": NOT_FOUND, "citations": [], "mode": "not_found"}  # no provider call`,
    },
  ],
  limitations: {
    fa: [
      "کورپوس فعلی از مستندات و محتوای همین سایت ساخته شده؛ اگر پاسخ در آن نباشد، دستیار پاسخ عمومی نمی‌سازد.",
      "دستیار جای پاسخ رسمی تیم را نمی‌گیرد و متن پرسش بدون رضایت شما ذخیره نمی‌شود.",
    ],
    en: [
      "The current corpus comes from this site's own content and documentation; when the answer is not there, the assistant does not invent one.",
      "The assistant does not replace an official answer from the team, and your question is not stored without consent.",
    ],
  },
  disclaimers: {
    fa: ["این پاسخ توسط مدل زبانی و فقط از روی مطالب امت تولید شده و ممکن است خطا داشته باشد."],
    en: ["This answer was generated by a language model from Emmett's own material and may contain mistakes."],
  },
  offlineCapable: false,
  noindexResults: true,
};

export default meta;
