"""Answer orchestration + the hard output filters.

Order of decisions (all enforced here, all tested):

1. cache lookup by hash of the *normalized* question → identical questions never pay twice;
2. retrieval with a similarity/coverage threshold → below it we answer «پیدا نکردم» and make
   **no provider call at all**;
3. budget/provider check → when the provider is unavailable or the daily cap is reached we answer
   from BM25 with an honest notice, never with a raw error;
4. output filter → an LLM answer without a citation that matches a retrieved chunk is discarded
   and replaced by «نمی‌دانم»;
5. every answer carries the AI disclosure and its citations.
"""

from __future__ import annotations

import hashlib
import time

from django.utils import timezone

from .models import AssistantQueryCache, AssistantUsage
from .providers import ProviderError, daily_cost_cap, estimate_cost, get_provider
from .retrieval import search

AI_DISCLOSURE_FA = "این پاسخ توسط مدل زبانی و فقط از روی مطالب امت تولید شده و ممکن است خطا داشته باشد."
AI_DISCLOSURE_EN = "This answer was generated by a language model from Emmett's own material and may contain mistakes."
NOT_FOUND_FA = "این را در مطالب ما پیدا نکردم."
NOT_FOUND_EN = "I could not find this in our material."
DEGRADED_FA = "پاسخ هوشمند موقتاً در دسترس نیست. این مطالب مرتبط را پیدا کردیم:"
DEGRADED_EN = "The AI answer is temporarily unavailable. Here is the related material we found:"
MAX_QUESTION_CHARS = 500
CITATION_LIMIT = 4


def normalize_question(question: str) -> str:
    from apps.tools.normalize import normalize_persian

    text = " ".join((question or "").split())
    return normalize_persian(text)["normalized"]


def question_hash(question: str, locale: str) -> str:
    return hashlib.sha256(f"{locale}:{normalize_question(question)}".encode("utf-8")).hexdigest()


def _citation(hit: dict) -> dict:
    return {
        "chunk_id": hit.get("chunk_id") or hit.get("id"),
        "title": hit.get("title") or hit.get("source", ""),
        "source": hit.get("source", ""),
        "url": hit.get("url", ""),
    }


def _public_retrieval(hits: list[dict]) -> list[dict]:
    return [
        {
            "chunk_id": hit.get("chunk_id") or hit.get("id"),
            "title": hit.get("title", ""),
            "source": hit.get("source", ""),
            "url": hit.get("url", ""),
            "score": hit.get("score", 0),
            "coverage": hit.get("coverage"),
            "excerpt": hit.get("text", "")[:280],
        }
        for hit in hits
    ]


def _bm25_answer(hits: list[dict], locale: str) -> str:
    heading = DEGRADED_FA if locale == "fa" else DEGRADED_EN
    lines = []
    for index, hit in enumerate(hits[:CITATION_LIMIT], start=1):
        title = hit.get("title") or hit.get("source")
        lines.append(f"[{index}] {title}")
    return heading + "\n" + "\n".join(lines)


def _not_found(locale: str, related: list[dict]) -> str:
    base = NOT_FOUND_FA if locale == "fa" else NOT_FOUND_EN
    return base


def _has_valid_citation(answer: str, citations: list[dict]) -> bool:
    if not answer.strip() or not citations:
        return False
    return any(f"[{index}]" in answer for index in range(1, len(citations) + 1))


def budget_available() -> bool:
    cap = daily_cost_cap()
    if cap <= 0:
        return False  # no budget configured → BM25 by default (B7 open)
    usage = AssistantUsage.today()
    return usage.cost_usd < cap


def answer_question(question: str, locale: str = "fa", use_cache: bool = True) -> dict:
    started = time.monotonic()
    if len(question or "") > MAX_QUESTION_CHARS:
        question = question[:MAX_QUESTION_CHARS]

    qhash = question_hash(question, locale)
    if use_cache:
        cached = AssistantQueryCache.objects.filter(query_hash=qhash).first()
        if cached is not None:
            return {
                "answer": cached.answer,
                "citations": cached.citations,
                "retrieval": cached.retrieval,
                "mode": cached.mode,
                "provider": "cache",
                "cached": True,
                "disclosure": AI_DISCLOSURE_FA if locale == "fa" else AI_DISCLOSURE_EN,
                "latency_ms": int((time.monotonic() - started) * 1000),
            }

    result = search(question, locale=locale)
    hits = result["hits"][:CITATION_LIMIT]
    citations = [_citation(hit) for hit in hits]
    retrieval = _public_retrieval(hits)

    if not hits:
        payload = {
            "answer": _not_found(locale, retrieval),
            "citations": [],
            "retrieval": [],
            "mode": "not_found",
            "provider": "none",
            "cached": False,
            "disclosure": AI_DISCLOSURE_FA if locale == "fa" else AI_DISCLOSURE_EN,
        }
    else:
        provider = get_provider()
        used_llm = False
        answer_text = ""
        provider_name = "bm25"
        if provider.available and budget_available():
            try:
                completion = provider.complete(_messages(question, locale, hits))
                usage = AssistantUsage.today()
                usage.requests += 1
                usage.prompt_tokens += completion.prompt_tokens
                usage.completion_tokens += completion.completion_tokens
                usage.cost_usd += estimate_cost(completion.prompt_tokens, completion.completion_tokens)
                usage.save()
                if _has_valid_citation(completion.text, citations):
                    answer_text, used_llm, provider_name = completion.text.strip(), True, provider.name
            except ProviderError:
                used_llm = False

        if used_llm:
            payload = {
                "answer": answer_text,
                "citations": citations,
                "retrieval": retrieval,
                "mode": "llm",
                "provider": provider_name,
                "cached": False,
                "disclosure": AI_DISCLOSURE_FA if locale == "fa" else AI_DISCLOSURE_EN,
            }
        else:
            # Either the provider is off/over budget, or its answer had no usable citation.
            payload = {
                "answer": _bm25_answer(hits, locale),
                "citations": citations,
                "retrieval": retrieval,
                "mode": "bm25",
                "provider": "bm25",
                "cached": False,
                "disclosure": AI_DISCLOSURE_FA if locale == "fa" else AI_DISCLOSURE_EN,
            }

    payload["latency_ms"] = int((time.monotonic() - started) * 1000)
    AssistantQueryCache.objects.update_or_create(
        query_hash=qhash,
        defaults={
            "locale": locale,
            "answer": payload["answer"],
            "citations": payload["citations"],
            "retrieval": payload["retrieval"],
            "mode": payload["mode"],
            "hits": len(hits),
        },
    )
    return payload


def _messages(question: str, locale: str, hits: list[dict]) -> list[dict]:
    context = "\n\n".join(
        f"[{index}] {hit.get('title')} ({hit.get('source')}): {hit.get('text')}"
        for index, hit in enumerate(hits, start=1)
    )
    if locale == "fa":
        system = (
            "فقط از متن داده‌شده پاسخ بده و هر ادعا را با شمارهٔ منبع مثل [1] مشخص کن. "
            "اگر پاسخ در متن نیست، دقیقاً بنویس: «این را در مطالب ما پیدا نکردم.» "
            "از دانش عمومی خودت استفاده نکن."
        )
    else:
        system = (
            "Answer only from the provided text and mark every claim with a source number like [1]. "
            "If the answer is not in the text, reply exactly: 'I could not find this in our material.' "
            "Never use outside knowledge."
        )
    return [
        {"role": "system", "content": system},
        {"role": "user", "content": f"Context:\n{context}\n\nQuestion: {question}"},
    ]


def refresh_embeddings(batch_size: int = 32, provider=None) -> dict:
    """Hash-based re-embedding (card test #9). Delegates to the indexer."""
    from .indexer import sync_corpus

    return sync_corpus(embed=True, batch_size=batch_size, provider=provider)


def purge_cache(older_than_days: int = 30) -> int:
    cutoff = timezone.now() - timezone.timedelta(days=older_than_days)
    deleted, _ = AssistantQueryCache.objects.filter(created_at__lt=cutoff).delete()
    return deleted
