# Generated by Django 5.2.6 on 2026-10-01 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssistantChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=240)),
                (
                    "locale",
                    models.CharField(
                        choices=[("fa", "Persian"), ("en", "English")], max_length=2
                    ),
                ),
                ("text", models.TextField()),
                ("embedding", models.BinaryField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="AssistantAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_hash", models.CharField(db_index=True, max_length=64)),
                ("answer", models.TextField(blank=True)),
                ("citations", models.JSONField(default=list)),
                ("provider", models.CharField(default="bm25", max_length=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="jobs.job"
                    ),
                ),
            ],
        ),
    ]
