# Generated by Django 5.2.17 on 2026-10-02 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helpful', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssistantQueryCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_hash', models.CharField(max_length=64, unique=True)),
                ('locale', models.CharField(default='fa', max_length=2)),
                ('answer', models.TextField()),
                ('citations', models.JSONField(default=list)),
                ('retrieval', models.JSONField(default=list)),
                ('mode', models.CharField(default='bm25', max_length=8)),
                ('hits', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssistantUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True)),
                ('requests', models.PositiveIntegerField(default=0)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='assistantchunk',
            options={'ordering': ['source', 'ordinal']},
        ),
        migrations.AddField(
            model_name='assistantanswer',
            name='cached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assistantanswer',
            name='latency_ms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assistantanswer',
            name='mode',
            field=models.CharField(default='bm25', max_length=8),
        ),
        migrations.AddField(
            model_name='assistantanswer',
            name='question_locale',
            field=models.CharField(default='fa', max_length=2),
        ),
        migrations.AddField(
            model_name='assistantanswer',
            name='retrieval',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='assistantchunk',
            name='content_hash',
            field=models.CharField(db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='assistantchunk',
            name='embed_provider',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='assistantchunk',
            name='kind',
            field=models.CharField(choices=[('doc', 'Documentation'), ('tool', 'Tool'), ('faq', 'FAQ')], default='doc', max_length=8),
        ),
        migrations.AddField(
            model_name='assistantchunk',
            name='ordinal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assistantchunk',
            name='title',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='assistantchunk',
            name='url',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='assistantchunk',
            name='locale',
            field=models.CharField(choices=[('fa', 'Persian'), ('en', 'English')], default='fa', max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='assistantchunk',
            unique_together={('source', 'ordinal')},
        ),
        migrations.AddIndex(
            model_name='assistantchunk',
            index=models.Index(fields=['kind', 'locale'], name='assistant_a_kind_e68883_idx'),
        ),
        migrations.AddField(
            model_name='assistantfeedback',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='assistant.assistantanswer'),
        ),
    ]
