# Generated by Django 5.2.17 on 2026-10-04 17:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_sitesettings_media_searchindexentry_translation'),
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='deleted at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('title', models.CharField(blank=True, default='', max_length=150, verbose_name='title')),
                ('title_fa', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='title')),
                ('title_en', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='title')),
                ('bio', models.TextField(blank=True, default='', verbose_name='bio')),
                ('bio_fa', models.TextField(blank=True, default='', null=True, verbose_name='bio')),
                ('bio_en', models.TextField(blank=True, default='', null=True, verbose_name='bio')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.media')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instructor',
                'verbose_name_plural': 'Instructors',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='deleted at')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20, verbose_name='status')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='published at')),
                ('meta_title', models.CharField(blank=True, default='', max_length=70, verbose_name='meta title')),
                ('meta_title_fa', models.CharField(blank=True, default='', max_length=70, null=True, verbose_name='meta title')),
                ('meta_title_en', models.CharField(blank=True, default='', max_length=70, null=True, verbose_name='meta title')),
                ('meta_description', models.CharField(blank=True, default='', max_length=160, verbose_name='meta description')),
                ('meta_description_fa', models.CharField(blank=True, default='', max_length=160, null=True, verbose_name='meta description')),
                ('meta_description_en', models.CharField(blank=True, default='', max_length=160, null=True, verbose_name='meta description')),
                ('canonical_path', models.CharField(blank=True, default='', help_text='در صورت خالی بودن، مسیر پیش\u200cفرض صفحه به\u200cعنوان canonical استفاده می\u200cشود.', max_length=255, verbose_name='canonical path')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('title_fa', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='slug')),
                ('summary', models.CharField(max_length=300, verbose_name='summary')),
                ('summary_fa', models.CharField(max_length=300, null=True, verbose_name='summary')),
                ('summary_en', models.CharField(max_length=300, null=True, verbose_name='summary')),
                ('description', models.TextField(blank=True, default='', verbose_name='description (Markdown)')),
                ('description_fa', models.TextField(blank=True, default='', null=True, verbose_name='description (Markdown)')),
                ('description_en', models.TextField(blank=True, default='', null=True, verbose_name='description (Markdown)')),
                ('description_html', models.TextField(blank=True, default='', editable=False)),
                ('description_html_fa', models.TextField(blank=True, default='', editable=False, null=True)),
                ('description_html_en', models.TextField(blank=True, default='', editable=False, null=True)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20, verbose_name='level')),
                ('duration_hours', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='duration (hours)')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='is featured')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='order')),
                ('categories', models.ManyToManyField(blank=True, related_name='courses', to='taxonomy.category')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.media')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.media', verbose_name='OG image')),
                ('tags', models.ManyToManyField(blank=True, related_name='courses', to='taxonomy.tag')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='academy.instructor')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['order', 'title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='deleted at')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('title_fa', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('summary', models.CharField(blank=True, default='', max_length=300, verbose_name='summary')),
                ('summary_fa', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='summary')),
                ('summary_en', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='summary')),
                ('content', models.TextField(blank=True, default='', verbose_name='content (Markdown)')),
                ('content_fa', models.TextField(blank=True, default='', null=True, verbose_name='content (Markdown)')),
                ('content_en', models.TextField(blank=True, default='', null=True, verbose_name='content (Markdown)')),
                ('content_html', models.TextField(blank=True, default='', editable=False)),
                ('content_html_fa', models.TextField(blank=True, default='', editable=False, null=True)),
                ('content_html_en', models.TextField(blank=True, default='', editable=False, null=True)),
                ('video_url', models.URLField(blank=True, default='', verbose_name='video URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='duration (minutes)')),
                ('is_preview', models.BooleanField(default=False, help_text='قابل\u200cمشاهده بدون نیاز به ورود/خرید.', verbose_name='is preview')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='academy.course')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'ordering': ['course', 'order'],
                'abstract': False,
                'unique_together': {('course', 'order')},
            },
        ),
    ]
