# Generated by Django 5.2.17 on 2026-10-04 17:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_sitesettings_media_searchindexentry_translation'),
        ('services', '0001_initial'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='deleted at')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20, verbose_name='status')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='published at')),
                ('meta_title', models.CharField(blank=True, default='', max_length=70, verbose_name='meta title')),
                ('meta_title_fa', models.CharField(blank=True, default='', max_length=70, null=True, verbose_name='meta title')),
                ('meta_title_en', models.CharField(blank=True, default='', max_length=70, null=True, verbose_name='meta title')),
                ('meta_description', models.CharField(blank=True, default='', max_length=160, verbose_name='meta description')),
                ('meta_description_fa', models.CharField(blank=True, default='', max_length=160, null=True, verbose_name='meta description')),
                ('meta_description_en', models.CharField(blank=True, default='', max_length=160, null=True, verbose_name='meta description')),
                ('canonical_path', models.CharField(blank=True, default='', help_text='در صورت خالی بودن، مسیر پیش\u200cفرض صفحه به\u200cعنوان canonical استفاده می\u200cشود.', max_length=255, verbose_name='canonical path')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('title_fa', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='slug')),
                ('summary', models.CharField(max_length=300, verbose_name='summary')),
                ('summary_fa', models.CharField(max_length=300, null=True, verbose_name='summary')),
                ('summary_en', models.CharField(max_length=300, null=True, verbose_name='summary')),
                ('client_name', models.CharField(blank=True, default='', max_length=150, verbose_name='client name')),
                ('year', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='year')),
                ('is_product', models.BooleanField(db_index=True, default=False, help_text='مثلاً Pentestor/CRM — محصولات داخلی که به شکل Project نمایش داده می\u200cشوند.', verbose_name='is product')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='is featured')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='order')),
                ('categories', models.ManyToManyField(blank=True, help_text='برای فیلتر «صنعت».', related_name='projects', to='taxonomy.category')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.media')),
                ('gallery', models.ManyToManyField(blank=True, related_name='project_galleries', to='core.media')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.media', verbose_name='OG image')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='services.service')),
                ('tags', models.ManyToManyField(blank=True, help_text='برای فیلتر «تکنولوژی».', related_name='projects', to='taxonomy.tag')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', '-year'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='deleted at')),
                ('challenge', models.TextField(blank=True, default='', verbose_name='challenge (Markdown)')),
                ('challenge_fa', models.TextField(blank=True, default='', null=True, verbose_name='challenge (Markdown)')),
                ('challenge_en', models.TextField(blank=True, default='', null=True, verbose_name='challenge (Markdown)')),
                ('challenge_html', models.TextField(blank=True, default='', editable=False)),
                ('challenge_html_fa', models.TextField(blank=True, default='', editable=False, null=True)),
                ('challenge_html_en', models.TextField(blank=True, default='', editable=False, null=True)),
                ('approach', models.TextField(blank=True, default='', verbose_name='approach (Markdown)')),
                ('approach_fa', models.TextField(blank=True, default='', null=True, verbose_name='approach (Markdown)')),
                ('approach_en', models.TextField(blank=True, default='', null=True, verbose_name='approach (Markdown)')),
                ('approach_html', models.TextField(blank=True, default='', editable=False)),
                ('approach_html_fa', models.TextField(blank=True, default='', editable=False, null=True)),
                ('approach_html_en', models.TextField(blank=True, default='', editable=False, null=True)),
                ('architecture_notes', models.TextField(blank=True, default='', verbose_name='architecture notes (Markdown)')),
                ('architecture_notes_fa', models.TextField(blank=True, default='', null=True, verbose_name='architecture notes (Markdown)')),
                ('architecture_notes_en', models.TextField(blank=True, default='', null=True, verbose_name='architecture notes (Markdown)')),
                ('architecture_notes_html', models.TextField(blank=True, default='', editable=False)),
                ('architecture_notes_html_fa', models.TextField(blank=True, default='', editable=False, null=True)),
                ('architecture_notes_html_en', models.TextField(blank=True, default='', editable=False, null=True)),
                ('technology_stack', models.JSONField(blank=True, default=list, verbose_name='technology stack')),
                ('implementation_notes', models.TextField(blank=True, default='', verbose_name='implementation notes (Markdown)')),
                ('implementation_notes_fa', models.TextField(blank=True, default='', null=True, verbose_name='implementation notes (Markdown)')),
                ('implementation_notes_en', models.TextField(blank=True, default='', null=True, verbose_name='implementation notes (Markdown)')),
                ('implementation_notes_html', models.TextField(blank=True, default='', editable=False)),
                ('implementation_notes_html_fa', models.TextField(blank=True, default='', editable=False, null=True)),
                ('implementation_notes_html_en', models.TextField(blank=True, default='', editable=False, null=True)),
                ('result', models.TextField(blank=True, default='', verbose_name='result (Markdown)')),
                ('result_fa', models.TextField(blank=True, default='', null=True, verbose_name='result (Markdown)')),
                ('result_en', models.TextField(blank=True, default='', null=True, verbose_name='result (Markdown)')),
                ('result_html', models.TextField(blank=True, default='', editable=False)),
                ('result_html_fa', models.TextField(blank=True, default='', editable=False, null=True)),
                ('result_html_en', models.TextField(blank=True, default='', editable=False, null=True)),
                ('metrics', models.JSONField(blank=True, default=dict, verbose_name='metrics')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case_study', to='portfolio.project')),
            ],
            options={
                'verbose_name': 'Case Study',
                'verbose_name_plural': 'Case Studies',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
