# Generated by Django 5.2.17 on 2026-10-04 17:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_sitesettings_media_searchindexentry_translation'),
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='deleted at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=150, verbose_name='full name')),
                ('role_title', models.CharField(max_length=150, verbose_name='role title')),
                ('role_title_fa', models.CharField(max_length=150, null=True, verbose_name='role title')),
                ('role_title_en', models.CharField(max_length=150, null=True, verbose_name='role title')),
                ('bio', models.TextField(blank=True, default='', verbose_name='bio')),
                ('bio_fa', models.TextField(blank=True, default='', null=True, verbose_name='bio')),
                ('bio_en', models.TextField(blank=True, default='', null=True, verbose_name='bio')),
                ('social_links', models.JSONField(blank=True, default=dict, verbose_name='social links')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='order')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.media')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_memberships', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'full_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='deleted at')),
                ('author_name', models.CharField(max_length=150, verbose_name='author name')),
                ('author_role', models.CharField(blank=True, default='', max_length=150, verbose_name='author role')),
                ('author_role_fa', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='author role')),
                ('author_role_en', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='author role')),
                ('author_company', models.CharField(blank=True, default='', max_length=150, verbose_name='author company')),
                ('quote', models.TextField(verbose_name='quote')),
                ('quote_fa', models.TextField(null=True, verbose_name='quote')),
                ('quote_en', models.TextField(null=True, verbose_name='quote')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='is featured')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='order')),
                ('author_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.media')),
                ('related_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='portfolio.project')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
    ]
