# Generated by Django 5.2.17 on 2026-10-04 17:36

import apps.leads.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='deleted at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='phone')),
                ('project_type', models.CharField(choices=[('website', 'Website'), ('mobile_app', 'Mobile App'), ('security', 'Security / Pentest'), ('crm', 'CRM'), ('consulting', 'Consulting'), ('other', 'Other')], max_length=20, verbose_name='project type')),
                ('budget_range', models.CharField(choices=[('under_50m', 'Under 50M Toman'), ('50_150m', '50-150M Toman'), ('150_500m', '150-500M Toman'), ('over_500m', 'Over 500M Toman'), ('not_sure', 'Not sure yet')], max_length=20, verbose_name='budget range')),
                ('timeline', models.CharField(choices=[('immediate', 'Immediate'), ('within_1_month', 'Within 1 month'), ('within_3_months', 'Within 3 months'), ('flexible', 'Flexible')], max_length=20, verbose_name='timeline')),
                ('message', models.TextField(max_length=5000, verbose_name='message')),
                ('source', models.CharField(choices=[('website_form', 'Website Form'), ('ai_assistant', 'AI Assistant'), ('referral', 'Referral')], default='website_form', max_length=20, verbose_name='source')),
                ('consent_given', models.BooleanField(default=False, verbose_name='consent given')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.CharField(blank=True, default='', max_length=500, verbose_name='user agent')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='deleted at')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='phone')),
                ('locale_preference', models.CharField(default='fa', max_length=5, verbose_name='locale preference')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='is confirmed')),
                ('confirmation_token', models.CharField(default=apps.leads.models.generate_confirmation_token, editable=False, max_length=64, unique=True)),
                ('subscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='subscribed at')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='unsubscribed at')),
            ],
            options={
                'verbose_name': 'Newsletter Subscription',
                'verbose_name_plural': 'Newsletter Subscriptions',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='deleted at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('proposal', 'Proposal'), ('won', 'Won'), ('lost', 'Lost')], db_index=True, default='new', max_length=20, verbose_name='status')),
                ('priority_score', models.IntegerField(default=0, verbose_name='priority score')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.contact')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-priority_score', '-created_at'],
                'abstract': False,
            },
        ),
    ]
