# Generated by Django 5.2.17 on 2026-10-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0002_jobapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailoutbox",
            name="locked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="newslettersubscriber",
            name="confirmation_token",
            field=models.CharField(blank=True, max_length=320),
        ),
    ]
