# Generated by Django 5.2.17 on 2026-10-02 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(unique=True)),
                ('version', models.CharField(max_length=32)),
                ('source', models.CharField(blank=True, max_length=240)),
                ('coverage', models.CharField(default='solar-fixed', max_length=32)),
                ('note_fa', models.CharField(blank=True, max_length=300)),
                ('note_en', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('day', models.PositiveSmallIntegerField()),
                ('label_fa', models.CharField(max_length=120)),
                ('label_en', models.CharField(blank=True, max_length=120)),
                ('kind', models.CharField(default='solar', max_length=16)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tools.holidaycalendar')),
            ],
            options={
                'ordering': ['month', 'day'],
                'unique_together': {('calendar', 'month', 'day')},
            },
        ),
    ]
