# Generated by Django 5.2.6 on 2026-10-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CaseStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("slug_fa", models.SlugField(blank=True)),
                ("title_fa", models.CharField(blank=True, max_length=240)),
                ("title_en", models.CharField(blank=True, max_length=240)),
                ("body_fa", models.TextField(blank=True)),
                ("body_en", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        db_index=True,
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JobOpening",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("slug_fa", models.SlugField(blank=True)),
                ("title_fa", models.CharField(blank=True, max_length=240)),
                ("title_en", models.CharField(blank=True, max_length=240)),
                ("body_fa", models.TextField(blank=True)),
                ("body_en", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        db_index=True,
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "salary_min_toman",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "salary_max_toman",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("slug_fa", models.SlugField(blank=True)),
                ("title_fa", models.CharField(blank=True, max_length=240)),
                ("title_en", models.CharField(blank=True, max_length=240)),
                ("body_fa", models.TextField(blank=True)),
                ("body_en", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        db_index=True,
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("category", models.CharField(blank=True, max_length=80)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SiteConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_en", models.CharField(default="Emmett", max_length=100)),
                ("brand_fa", models.CharField(default="امت", max_length=100)),
                ("telegram_handle", models.CharField(blank=True, max_length=80)),
                ("building_fa", models.CharField(blank=True, max_length=240)),
                ("building_en", models.CharField(blank=True, max_length=240)),
            ],
            options={
                "verbose_name": "Site configuration",
                "verbose_name_plural": "Site configuration",
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_fa", models.CharField(max_length=160)),
                ("name_en", models.CharField(blank=True, max_length=160)),
                ("role_fa", models.CharField(max_length=160)),
                ("role_en", models.CharField(blank=True, max_length=160)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quote_fa", models.TextField()),
                ("quote_en", models.TextField(blank=True)),
                ("attribution_fa", models.CharField(max_length=200)),
                ("attribution_en", models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
