# Generated by Django 5.2.17 on 2026-10-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_category_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='lab_samples_per_day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='lab_tests_per_sample',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='lab_turnaround_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
