# Generated by Django 5.2.17 on 2026-10-02 07:31

import apps.scanner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scanresult',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='scanresult',
            name='blocklist_version',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='expires_at',
            field=models.DateTimeField(default=apps.scanner.models.result_expiry),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='result_id',
            field=models.CharField(db_index=True, default=apps.scanner.models.new_result_id, max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.CreateModel(
            name='BlocklistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(db_index=True, max_length=32)),
                ('kind', models.CharField(choices=[('gov', 'Sensitive government'), ('private', 'Private / RFC1918 / localhost'), ('bulk', 'Mass-scan pattern'), ('custom', 'Custom')], max_length=16)),
                ('pattern', models.CharField(help_text='suffix match, or regex when kind=bulk', max_length=200)),
                ('note_fa', models.CharField(blank=True, max_length=200)),
                ('note_en', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['kind', 'pattern'],
                'unique_together': {('version', 'pattern')},
            },
        ),
    ]
